apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aio-mq-pubsub
  namespace: azure-iot-operations
  annotations:
    dapr.io/component-container: >
      {
        "name": "iot-operations-dapr-components",
        "image": "ghcr.io/azure/iot-operations-dapr-components:latest",
        "volumeMounts": [
          { "name": "daprworkflow-client-token", "mountPath": "/var/run/secrets/tokens" },
          { "name": "aio-ca-trust-bundle", "mountPath": "/var/run/certs/aio-internal-ca-cert" }
        ]
      }
spec:
  type: pubsub.azure.iotoperations
  version: v1
  metadata:
  - name: hostname
    value: aio-broker
  - name: tcpPort
    value: 18883
  - name: useTls
    value: true
  - name: caFile
    value: /var/run/certs/aio-internal-ca-cert/ca.crt
  - name: satAuthFile
    value: /var/run/secrets/tokens/daprworkflow-client-token
# State Management component
# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: aio-mq-statestore
#   namespace: azure-iot-operations
#   annotations:
#     dapr.io/component-container: >
#       {
#         "name": "aio-mq-components",
#         "image": "ghcr.io/azure/iot-mq-dapr-components:latest",
#         "volumeMounts": [
#           {
#             "name": "daprworkflow-client-token",
#             "mountPath": "/var/run/secrets/tokens"
#           },
#           {
#             "name": "aio-ca-trust-bundle",
#             "mountPath": "/var/run/certs/aio-mq-ca-cert"
#           }
#         ]
#       }
# spec:
#   type: state.aio-mq-statestore-pluggable # DO NOT CHANGE
#   version: v1
#   metadata:
#   - name: url
#     value: "aio-mq-dmqtt-frontend:8883"
#   - name: satTokenPath
#     value: "/var/run/secrets/tokens/daprworkflow-client-token"
#   - name: tlsEnabled
#     value: true
#   - name: caCertPath
#     value: "/var/run/certs/aio-mq-ca-cert/ca.crt"
  # - name: actorStateStore
  #   value: "true"